/**
 * BullBridge — SEBI Compliance & Risk Disclaimer
 */

import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { Stack, router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../theme/ThemeProvider';
import { ThemeColors } from '../../constants/colors';
import { Typography, Spacing, BorderRadius } from '../../constants/theme';

export default function SebiDisclaimerScreen() {
  const { theme } = useTheme();
  const styles = getStyles(theme);

  return (
    <View style={styles.container}>
      <Stack.Screen options={{ 
        headerTitle: 'SEBI Disclaimer',
        headerLeft: () => (
          <TouchableOpacity onPress={() => router.back()}>
            <Ionicons name="arrow-back" size={24} color={theme.textPrimary} />
          </TouchableOpacity>
        ),
      }} />
      
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.warningBox}>
          <Ionicons name="warning" size={32} color={theme.warning} />
          <Text style={styles.warningTitle}>Risk Disclosure</Text>
        </View>

        <Text style={styles.sectionTitle}>SEBI Registration</Text>
        <Text style={styles.paragraph}>
          BullBridge is an AI-powered analytics platform. We are NOT SEBI-registered investment advisors or research analysts. All predictions generated by our LSTM, XGBoost, and Ensemble models are for educational and backtesting purposes only.
        </Text>

        <Text style={styles.sectionTitle}>No Recommendations</Text>
        <Text style={styles.paragraph}>
          The symbols "BULLISH" and "BEARISH" used in the app are model outputs and should NOT be considered as "Buy" or "Sell" recommendations. Users are advised to consult with a certified financial planner before making any investment decisions.
        </Text>

        <Text style={styles.sectionTitle}>Data Lag</Text>
        <Text style={styles.paragraph}>
          Live data is subject to a 15-minute delay from the exchange (NSE/BSE) as per Yahoo Finance's free data policy. We are not liable for any losses due to data latency.
        </Text>

        <Text style={styles.sectionTitle}>Past Performance</Text>
        <Text style={styles.paragraph}>
          Past performance of AI models is not indicative of future results. Stock market investments are subject to market risks. Please read all scheme related documents carefully before investing.
        </Text>

        <TouchableOpacity 
          style={styles.ackButton}
          onPress={() => router.back()}
        >
          <Text style={styles.ackButtonText}>I Understand the Risks</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const getStyles = (theme: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background },
  content: { padding: Spacing.xl, paddingBottom: 60 },
  warningBox: { 
    backgroundColor: theme.warningMuted, padding: Spacing.lg, borderRadius: BorderRadius.lg, 
    alignItems: 'center', marginBottom: Spacing.xl, borderWidth: 1, borderColor: 'rgba(255, 179, 0, 0.2)'
  },
  warningTitle: { fontSize: Typography.xl, fontWeight: Typography.bold, color: theme.warning, marginTop: Spacing.sm },
  sectionTitle: { fontSize: Typography.lg, fontWeight: Typography.bold, color: theme.textPrimary, marginTop: Spacing.lg, marginBottom: Spacing.sm },
  paragraph: { fontSize: Typography.base, color: theme.textSecondary, lineHeight: 22, marginBottom: Spacing.base },
  ackButton: {
    marginTop: Spacing['2xl'], backgroundColor: theme.primary,
    paddingVertical: Spacing.md, borderRadius: BorderRadius.lg,
    alignItems: 'center',
  },
  ackButtonText: { color: theme.textInverse, fontWeight: Typography.bold, fontSize: Typography.md },
});
